Repository everoute/everoute, pull requests merged in 2023-07, with the labels that each got.

#681 fix: update service ports, global whitelist doesn't update
  plugin/tower/pkg/controller/policy/controller.go
  plugin/tower/pkg/controller/policy/controller_test.go
Labels: size/s

#684 fix(policy-controller): wait for all informers sync before start controllers
  pkg/agent/controller/policy/policy_controller.go
  pkg/source/kind.go
  pkg/source/kind_test.go
Labels: size/s

#683 fix: ip migration in different vm
  pkg/agent/controller/policy/cache/group.go
  pkg/agent/controller/policy/cache/rule_test.go
  pkg/agent/controller/policy/policy_controller.go
  pkg/agent/controller/policy/policy_controller_helper.go
Labels: size/m

#685 feat(ut): add nextpatch unit test
  pkg/agent/controller/policy/cache/group_test.go
Labels: size/xs

#686 feat: export SetToken api for existed token
  plugin/tower/pkg/client/client.go
Labels: size/xs
