Repository everoute/everoute, pull requests merged in 2023-02, with the labels that each got.

#587 ci: the release action auto generate changelog
  .github/workflows/build.yaml
Labels: size/xs

#590 refactor(plugin-tower): streaming upload file with graphql
  plugin/tower/pkg/client/client.go
  plugin/tower/pkg/client/client_test.go
  plugin/tower/pkg/client/request.go
  plugin/tower/pkg/client/request_test.go
Labels: size/l

#595 fix(dp): reset port no flood while reply flows
  pkg/agent/datapath/multiBridgeDatapath.go
Labels: size/s

#592 test: move e2e test into container
  .github/workflows/ci.yaml
  Makefile
  build/images/unit-test/Dockerfile
  build/images/unit-test/docker-entrypoint.sh
Labels: size/s

#594 fix(cni): check cni enable while reply flows
  pkg/agent/datapath/clsBridge.go
  pkg/agent/datapath/localBridge.go
Labels: size/s

#596 fix: update flowID reference while reply flows
  pkg/agent/datapath/multiBridgeDatapath.go
Labels: size/xs

#598 ci: helm chart package and push in workflow
  .github/workflows/build.yaml
Labels: size/s

#600 fix(plugin-tower): handle default apply type
  plugin/tower/pkg/controller/policy/controller.go
  plugin/tower/pkg/controller/policy/controller_test.go
Labels: size/s

#588 feat(cni): add svcindex struct and its method
  pkg/agent/datapath/cache/svc_index.go
  pkg/agent/datapath/cache/svc_ovs_info.go
  pkg/agent/datapath/natBridge.go
Labels: size/m

#601 feat(cni): genServicePort
  cmd/everoute-controller/main.go
  deploy/chart/crds/service.everoute.io_serviceports.yaml
  deploy/chart/templates/controller/controller.yaml
  deploy/chart/templates/controller/role.yaml
  deploy/everoute.yaml
  pkg/apis/service/v1alpha1/types.go
  pkg/controller/k8s/endpoints_controller.go
  pkg/controller/k8s/endpoints_controller_test.go
  pkg/controller/k8s/suite_test.go
Labels: size/l

#605 fix(cni): pod add liveness probe
  deploy/chart/templates/agent/agent.yaml
  deploy/chart/templates/controller/controller.yaml
  deploy/everoute.yaml
Labels: size/s

#606 feat(agent-monitor): only notify sync agentinfo on new address
  pkg/monitor/agent.go
Labels: size/s

#607 feat(agent-monitor): only notify sync agentinfo on new address
  pkg/monitor/agent.go
Labels: size/s

#603 fix(policy): filter DROP policy in EST ct item
  go.mod
  go.sum
  pkg/agent/datapath/policyBridge.go
Labels: size/s

#609 fix: reduce requeue time limit to 1 nanosecond
  pkg/agent/controller/policy/policy_controller.go
  pkg/controller/group/group_controller.go
Labels: size/s

#608 fix: reduce requeue time limit to 1 nanosecond
  pkg/agent/controller/policy/policy_controller.go
  pkg/controller/group/group_controller.go
Labels: size/s

#615 fix(plugin-tower): handle zero length selector
  deploy/chart/crds/group.everoute.io_endpointgroups.yaml
  deploy/chart/crds/security.everoute.io_securitypolicies.yaml
  deploy/everoute.yaml
  pkg/labels/selector.go
  pkg/labels/selector_test.go
  plugin/tower/pkg/controller/policy/controller.go
  plugin/tower/pkg/controller/policy/controller_test.go
Labels: size/m

#619 fix(plugin-tower): handle zero length selector
  deploy/chart/crds/group.everoute.io_endpointgroups.yaml
  deploy/chart/crds/security.everoute.io_securitypolicies.yaml
  deploy/everoute.yaml
  pkg/labels/selector.go
  pkg/labels/selector_test.go
  plugin/tower/pkg/controller/policy/controller.go
  plugin/tower/pkg/controller/policy/controller_test.go
Labels: size/m

#583 feat(cni): generate BaseSvc cache and push service cluster ip flow
  cmd/everoute-agent/main.go
  cmd/everoute-controller/main.go
  deploy/chart/crds/service.everoute.io_serviceports.yaml
  deploy/chart/templates/agent/role.yaml
  deploy/everoute.yaml
  pkg/agent/controller/proxy/cache/backend_cache.go
  pkg/agent/controller/proxy/cache/service_cache.go
  pkg/agent/controller/proxy/cache/service_port_cache.go
  pkg/agent/controller/proxy/controller.go
  pkg/agent/datapath/baseBridge.go
  pkg/agent/datapath/cache/svc_ovs_info.go
  pkg/agent/datapath/id_generate.go
  pkg/agent/datapath/multiBridgeDatapath.go
  pkg/agent/datapath/natBridge.go
  pkg/agent/datapath/utils.go
  pkg/apis/service/v1alpha1/types.go
  pkg/controller/k8s/endpoints_controller.go
  pkg/controller/k8s/endpoints_controller_test.go
  pkg/controller/k8s/suite_test.go
  pkg/openapi/openapi_generated.go
Labels: size/l

#623 feat(rpc): return flow id in Get-Policy interface
  pkg/agent/datapath/multiBridgeDatapath.go
  pkg/agent/rpcserver/collector.go
  pkg/apis/rpc/v1alpha1/collector.pb.go
  pkg/apis/rpc/v1alpha1/collector.proto
Labels: size/xs

#621 fix: sync libopenflow with deadlock fix
  go.mod
  go.sum
Labels: size/xs

#622 test(cni): add proxy unittest frame
  pkg/agent/controller/proxy/controller_test.go
  pkg/agent/controller/proxy/suit_test.go
Labels: size/m

#628 feat(monitor): only learn global unicast ip
  pkg/monitor/agent.go
Labels: size/xs

#629 feat(monitor): only learn global unicast ip
  pkg/monitor/agent.go
Labels: size/xs, everoute/1.1, pick

#630 ci: ignore test file in pr size check
  .github/workflows/labeler.yaml
Labels: size/xs

#631 feat(plugin-tower): add original name in vm type
  plugin/tower/pkg/schema/types.go
Labels: area/visualization

#599 refactor(monitor): update ovsdb event
  pkg/agent/datapath/multiBridgeDatapath.go
  pkg/agent/datapath/multiBridgeDatapath_test.go
  pkg/monitor/agent_test.go
  pkg/monitor/ovsdb.go
  pkg/monitor/ovsdb_test.go
  pkg/monitor/suite_test.go
Labels: size/l

#633 feat(cni): fliter invalid servicePort backend
  pkg/agent/controller/proxy/cache/service_cache.go
  pkg/controller/k8s/endpoints_controller.go
  pkg/controller/k8s/endpoints_controller_test.go
Labels: size/s, area/cni
