Repository everoute/everoute, pull requests merged in 2023-01, with the labels that each got.

#571 fix: clean all related ct flow when policy changed
  pkg/agent/datapath/multiBridgeDatapath.go
Labels: bug

#576 add agent all options
  cmd/everoute-agent/config.go
  cmd/everoute-agent/main.go
Labels: feat

#573 push image to smtx.io
  .github/workflows/build.yaml
Labels: CNI

#575 init bridge nat
  build/script/init_agent
  pkg/agent/datapath/id_generate.go
  pkg/agent/datapath/multiBridgeDatapath.go
  pkg/agent/datapath/natBridge.go
  pkg/agent/datapath/utils.go
  pkg/agent/datapath/utils_test.go
Labels: CNI, size/l

#586 ci: ignore generated files in pr size check
  .github/workflows/labeler.yaml
Labels: size/xs
