Repository everoute/everoute, pull requests merged in 2023-08, with the labels that each got.

#687 fix(cni):delete expired iptables in EVEROUTE-OUTPUT chain
  pkg/agent/proxy/route.go
Labels: size/m

#689 fix: clean ct blocked er-489
  pkg/agent/controller/policy/policy_controller.go
  pkg/agent/datapath/multiBridgeDatapath.go
Labels: size/s

#691 feat(cni): add controller config
  Makefile
  cmd/everoute-agent/config.go
  cmd/everoute-controller/config.go
  cmd/everoute-controller/main.go
  deploy/chart/templates/agent/agent.yaml
  deploy/chart/templates/config.yaml
  deploy/chart/templates/controller/controller.yaml
  deploy/chart/values.yaml
  deploy/everoute.yaml
  pkg/constants/constants.go
Labels: CNI, size/m

#692 feat(cni): add overlay route and iptables
  cmd/everoute-agent/config.go
  cmd/everoute-agent/main.go
  go.mod
  go.sum
  pkg/agent/datapath/multiBridgeDatapath.go
  pkg/agent/proxy/iptables/base.go
  pkg/agent/proxy/iptables/overlay_mode.go
  pkg/agent/proxy/iptables/proxy_iptables.go
  pkg/agent/proxy/iptables/route_mode.go
  pkg/agent/proxy/route.go
Labels: CNI, size/l

#696 feat(cni): manager gw endpoint
  cmd/everoute-agent/main.go
  cmd/everoute-controller/main.go
  deploy/chart/templates/agent/agent.yaml
  deploy/chart/templates/agent/role.yaml
  deploy/chart/templates/controller/controller.yaml
  deploy/everoute.yaml
  pkg/constants/constants.go
  pkg/controller/k8s/node_controller.go
  pkg/controller/k8s/node_controller_test.go
  pkg/controller/k8s/suite_test.go
  pkg/utils/cni.go
Labels: CNI, size/m

#699 feat(cni): add tunnel port in init_agent
  build/images/release/Dockerfile
  build/script/init_agent
Labels: CNI, size/s

#701 feat: support VRRP protocol
  deploy/chart/crds/group.everoute.io_groupmembers.yaml
  deploy/chart/crds/group.everoute.io_groupmemberspatches.yaml
  deploy/chart/crds/security.everoute.io_endpoints.yaml
  deploy/chart/crds/security.everoute.io_securitypolicies.yaml
  deploy/everoute.yaml
  docs/content/en/docs/reference/apidocs.html
  pkg/agent/controller/policy/policy_controller_helper.go
  pkg/apis/security/v1alpha1/types.go
  pkg/openapi/openapi_generated.go
Labels: size/s

#702 build: allow disable auto server tls
  .github/workflows/build.yaml
  .github/workflows/labeler.yaml
  Makefile
  cmd/everoute-controller/main.go
  deploy/chart/templates/agent/agent.yaml
  deploy/chart/templates/controller/controller.yaml
  deploy/chart/templates/controller/webhook.yaml
  deploy/chart/templates/crds/agent.everoute.io_agentinfos.yaml
  deploy/chart/templates/crds/group.everoute.io_endpointgroups.yaml
  deploy/chart/templates/crds/group.everoute.io_groupmembers.yaml
  deploy/chart/templates/crds/group.everoute.io_groupmemberspatches.yaml
  deploy/chart/templates/crds/security.everoute.io_endpoints.yaml
  deploy/chart/templates/crds/security.everoute.io_globalpolicies.yaml
  deploy/chart/templates/crds/security.everoute.io_securitypolicies.yaml
  deploy/chart/templates/crds/service.everoute.io_serviceports.yaml
  deploy/chart/values.yaml
  deploy/everoute.yaml
  pkg/agent/controller/policy/suite_test.go
  pkg/agent/controller/proxy/suit_test.go
  pkg/controller/group/suite_test.go
  pkg/controller/k8s/suite_test.go
  pkg/controller/policy/suite_test.go
  pkg/webhook/validates/suite_test.go
  tests/e2e/scripts/controlplane-setup.sh
Labels: size/m

#700 feat(cni): init local bridge for overlay
  .github/workflows/ci.yaml
  .golangci.yml
  build/images/release/Dockerfile
  build/images/unit-test/Dockerfile
  cmd/everoute-agent/config.go
  go.mod
  go.sum
  pkg/agent/datapath/baseBridge.go
  pkg/agent/datapath/cache/svc_ovs_info.go
  pkg/agent/datapath/clsBridge.go
  pkg/agent/datapath/id_generate.go
  pkg/agent/datapath/localBridge.go
  pkg/agent/datapath/localBridgeOverlay.go
  pkg/agent/datapath/multiBridgeDatapath.go
  pkg/agent/datapath/multiBridgeDatapath_test.go
  pkg/agent/datapath/natBridge.go
  pkg/agent/datapath/policyBridge.go
  pkg/agent/datapath/uplinkBridge.go
  pkg/agent/datapath/utils.go
  pkg/agent/proxy/iptables/base.go
  pkg/agent/proxy/iptables/overlay_mode.go
  pkg/agent/proxy/route.go
  pkg/constants/constants.go
Labels: CNI, size/l

#697 watch Endpoint and node to get Pod IP and it's node IP
  cmd/everoute-agent/main.go
  pkg/agent/controller/overlay/cache/node_ips.go
  pkg/agent/controller/overlay/controller.go
  pkg/agent/controller/overlay/controller_test.go
  pkg/agent/controller/overlay/predicate.go
  pkg/agent/controller/overlay/predicate_test.go
  pkg/agent/controller/overlay/suit_test.go
  pkg/agent/proxy/route.go
  pkg/utils/cni.go
Labels: CNI, size/l
