Repository everoute/everoute, pull requests merged in 2023-03, with the labels that each got.

#612 feat: vlan trunk list filter
  pkg/agent/datapath/localBridge.go
  pkg/agent/datapath/multiBridgeDatapath_test.go
  pkg/agent/datapath/utils.go
  pkg/agent/datapath/utils_test.go
Labels: size/m

#640 fix(monitor): check endpoint ready before update endpoint
  pkg/monitor/ovsdb.go
Labels: size/s

#639 fix: upgrade dependencies
  cmd/everoute-agent/config.go
  go.mod
  go.sum
  tests/e2e/framework/config/config.go
Labels: size/s

#642 ci: pre-check runner change to self-hosted pod
  .github/workflows/ci.yaml
Labels: size/xs

#627 feat(cni): watch service change and update ovs flow
  pkg/agent/controller/proxy/cache/service_cache.go
  pkg/agent/controller/proxy/cache/service_cache_test.go
  pkg/agent/controller/proxy/controller.go
  pkg/agent/controller/proxy/controller_test.go
  pkg/agent/controller/proxy/suit_test.go
  pkg/agent/datapath/cache/svc_index.go
  pkg/agent/datapath/cache/svc_ovs_info.go
  pkg/agent/datapath/natBridge.go
Labels: size/l, area/cni

#591 feat(cni): add l3forward flow
  cmd/everoute-agent/config.go
  cmd/everoute-agent/main.go
  pkg/agent/datapath/localBridge.go
  pkg/agent/datapath/multiBridgeDatapath.go
  pkg/agent/datapath/natBridge.go
  pkg/agent/rpcserver/cni.go
  pkg/monitor/agent.go
  pkg/monitor/helper.go
  pkg/monitor/ovsdb.go
  pkg/monitor/ovsdb_test.go
  pkg/monitor/suite_test.go
  pkg/utils/ip.go
Labels: size/m, area/cni

#650 fix(cni): set bridge internal port rp_filter=1
  build/script/init_agent
Labels: size/s

#649 feat(cni): gen svcport name from svcname and portname
  pkg/controller/k8s/endpoints_controller.go
Labels: size/s

#651 fix: remove unused flowReplayChan from datapathManager
  pkg/agent/datapath/multiBridgeDatapath.go
Labels: size/xs

#641 feat(cni): everouter-controller use hostnetwork
  deploy/chart/templates/controller/controller.yaml
  deploy/everoute.yaml
Labels: size/xs

#652 feat(cni): set enableProxy default value is false
  deploy/chart/templates/controller/controller.yaml
  deploy/chart/values.yaml
  deploy/everoute.yaml
Labels: size/xs

#653 feat(cni): add deletecollection premission to controller
  deploy/chart/templates/controller/role.yaml
  deploy/everoute.yaml
Labels: size/xs

#657 test(cni): fix proxy unit test case for servicePort without service
  pkg/agent/controller/proxy/controller_test.go
Labels: size/xs

#632 feat(cni): process service flow in local bridge
  build/script/init_agent
  cmd/everoute-agent/config.go
  pkg/agent/datapath/localBridge.go
  pkg/agent/datapath/multiBridgeDatapath.go
  pkg/agent/datapath/natBridge.go
  pkg/agent/proxy/route.go
Labels: size/m, area/cni
