Repository everoute/everoute, pull requests merged in 2023-05, with the labels that each got.

#659 feat(alg): support ftp and tftp
  build/script/init_agent
  cmd/everoute-agent/main.go
  go.mod
  go.sum
  pkg/agent/datapath/multiBridgeDatapath.go
  pkg/agent/datapath/policyBridge.go
  pkg/constants/constants.go
  pkg/healthz/healthz.go
  plugin/tower/pkg/controller/policy/controller.go
  plugin/tower/pkg/controller/policy/controller_test.go
  plugin/tower/pkg/schema/policy_types.go
Labels: size/m

#666 change test image to smartx harbor
  .github/workflows/ci.yaml
  Makefile
  hack/0001-test-e2e-image.patch
Labels: size/s

#667 feat(alg): support AlgProtocol field
  plugin/tower/pkg/controller/policy/controller.go
  plugin/tower/pkg/controller/policy/controller_test.go
  plugin/tower/pkg/schema/policy_types.go
  plugin/tower/pkg/schema/policy_types.graphqls
  plugin/tower/pkg/server/fake/graph/generated/generated.go
  plugin/tower/pkg/utils/testing/builder.go
Labels: size/s

#665 feat: support service
  plugin/tower/pkg/controller/policy/controller.go
  plugin/tower/pkg/controller/policy/controller_test.go
  plugin/tower/pkg/informer/factory.go
  plugin/tower/pkg/schema/policy_types.go
  plugin/tower/pkg/schema/policy_types.graphqls
  plugin/tower/pkg/server/fake/graph/generated/generated.go
  plugin/tower/pkg/server/fake/graph/model/models_gen.go
  plugin/tower/pkg/server/fake/graph/query.graphqls
  plugin/tower/pkg/server/fake/graph/resolver/query.resolvers.go
  plugin/tower/pkg/server/fake/graph/resolver/tracker/factory.go
  plugin/tower/pkg/utils/testing/builder.go
Labels: size/m

#664 feat(e2e): add ftp e2e
  go.mod
  go.sum
  plugin/tower/pkg/controller/policy/controller_test.go
  tests/e2e/cases/security_test.go
  tests/e2e/framework/endpoint/manager.go
  tests/e2e/framework/endpoint/netns/provider.go
  tests/e2e/framework/endpoint/netns/scripts.go
  tests/e2e/framework/model/endpoint.go
  tests/e2e/scripts/e2e-setup.sh
  tests/e2e/tools/e2ectl/command/endpoint.go
  tests/e2e/tools/e2ectl/command/reach.go
  tests/e2e/tools/net-utils/command/connect.go
  tests/e2e/tools/net-utils/command/server.go
Labels: size/m

#670 feat: user-defined global whitelist support policy mode
  plugin/tower/pkg/controller/policy/controller.go
  plugin/tower/pkg/controller/policy/controller_test.go
Labels: size/s

#669 ci: add timeout for k8s e2e
  .github/workflows/ci.yaml
Labels: size/xs

#668 feat: support ipip
  deploy/chart/crds/group.everoute.io_groupmembers.yaml
  deploy/chart/crds/group.everoute.io_groupmemberspatches.yaml
  deploy/chart/crds/security.everoute.io_endpoints.yaml
  deploy/chart/crds/security.everoute.io_securitypolicies.yaml
  deploy/everoute.yaml
  docs/content/en/docs/reference/apidocs.html
  pkg/agent/controller/policy/policy_controller_helper.go
  pkg/apis/security/v1alpha1/types.go
  plugin/tower/pkg/controller/policy/controller.go
  plugin/tower/pkg/schema/policy_types.go
  plugin/tower/pkg/schema/policy_types.graphqls
  plugin/tower/pkg/server/fake/graph/generated/generated.go
  tests/e2e/cases/security_test.go
  tests/e2e/framework/endpoint/manager.go
Labels: size/s

#671 feat: peer support disable symmetric
  deploy/chart/crds/security.everoute.io_securitypolicies.yaml
  deploy/everoute.yaml
  docs/content/en/docs/reference/apidocs.html
  pkg/agent/controller/policy/cache/rule.go
  pkg/agent/controller/policy/policy_controller.go
  pkg/agent/controller/policy/policy_controller_test.go
  pkg/apis/security/v1alpha1/types.go
  pkg/openapi/openapi_generated.go
  plugin/tower/pkg/controller/policy/controller.go
  plugin/tower/pkg/controller/policy/controller_test.go
  plugin/tower/pkg/schema/policy_types.go
  plugin/tower/pkg/schema/policy_types.graphqls
  plugin/tower/pkg/server/fake/graph/generated/generated.go
  plugin/tower/pkg/utils/testing/builder.go
  tests/e2e/cases/security_test.go
  tests/e2e/framework/framework.go
Labels: size/m

#672 feat: support tier-ecp for ecp network policy
  deploy/chart/crds/security.everoute.io_securitypolicies.yaml
  deploy/everoute.yaml
  docs/content/en/docs/reference/apidocs.html
  pkg/agent/controller/policy/policy_controller_helper.go
  pkg/agent/datapath/multiBridgeDatapath.go
  pkg/agent/datapath/multiBridgeDatapath_test.go
  pkg/agent/datapath/policyBridge.go
  pkg/apis/security/v1alpha1/types.go
  pkg/constants/constants.go
  pkg/openapi/openapi_generated.go
  pkg/webhook/validates/crd_validate.go
  pkg/webhook/validates/crd_validate_test.go
  tests/e2e/cases/security_test.go
  tests/e2e/framework/endpoint/netns/provider.go
  tests/e2e/framework/endpoint/tower/provider.go
Labels: size/s

#655 Patch update pr size action
  .github/workflows/labeler.yaml
Labels: size/xs, area/ci
