Repository everoute/everoute, pull requests merged in 2023-11, with the labels that each got.

#728 upgrade k8s
  .typos.toml
  Makefile
  build/images/generate/Dockerfile
  cmd/everoute-agent/main.go
  deploy/chart/templates/controller/role.yaml
  deploy/chart/templates/crds/security.everoute.io_securitypolicies.yaml
  deploy/everoute.yaml
  go.mod
  go.sum
  pkg/agent/controller/overlay/controller.go
  pkg/agent/controller/overlay/predicate.go
  pkg/agent/controller/overlay/predicate_test.go
  pkg/agent/controller/overlay/suit_test.go
  pkg/agent/controller/policy/cache/rule.go
  pkg/agent/controller/policy/global_policy_controller.go
  pkg/agent/controller/policy/policy_controller.go
  pkg/agent/controller/policy/suite_test.go
  pkg/agent/controller/proxy/controller.go
  pkg/agent/controller/proxy/suit_test.go
  pkg/agent/proxy/route.go
  pkg/controller/common/webhook_controller.go
  pkg/controller/endpoint/endpoint_controller.go
  pkg/controller/endpoint/endpoint_controller_perf_test.go
  pkg/controller/endpoint/endpoint_controller_test.go
  pkg/controller/group/group_controller.go
  pkg/controller/group/group_controller_test.go
  pkg/controller/k8s/endpoints_controller.go
  pkg/controller/k8s/endpoints_controller_test.go
  pkg/controller/k8s/network_policy_controller.go
  pkg/controller/k8s/node_controller.go
  pkg/controller/k8s/pod_controller.go
  pkg/controller/policy/group_generator.go
  pkg/controller/policy/policy_controller.go
  pkg/healthz/healthz.go
  pkg/healthz/healthz_test.go
  pkg/openapi/openapi_generated.go
  pkg/source/event.go
  pkg/source/kind.go
  pkg/source/kind_test.go
  pkg/webhook/validates/crd_validate.go
  pkg/webhook/validates/crd_validate_test.go
  plugin/tower/pkg/informer/reflector.go
  plugin/tower/pkg/informer/reflector_test.go
  plugin/tower/pkg/register/manager.go
  plugin/tower/pkg/server/fake/graph/generated/generated.go
  plugin/tower/pkg/server/fake/graph/resolver/query.resolvers.go
  plugin/tower/pkg/server/fake/graph/resolver/types.resolvers.go
  plugin/tower/third_party/forked/client-go/informer/controller.go
  plugin/tower/third_party/forked/client-go/informer/reflector.go
  plugin/tower/third_party/forked/client-go/informer/shared_informer.go
  tests/e2e/cases/e2e_test.go
  tests/e2e/cases/security_test.go
  tests/e2e/framework/endpoint/tower/models.go
  tests/e2e/framework/endpoint/tower/tower.go
  tests/e2e/framework/framework.go
Labels: size/xl

#729 build: support build image with cni resource
  build/images/release-nocni/Dockerfile
Labels: size/s

#731 fix: fix tls cipher vulnerability
  cmd/everoute-controller/main.go
Labels: size/xs

#734 feat(cni): upgrade ovs to 2.17
  build/images/release/Dockerfile
  build/images/unit-test/Dockerfile
Labels: size/s

#736 ci: k8s e2e 1.25 sks 1.1
  .github/workflows/ci.yaml
  hack/0001-test-e2e-add-sleep-before-cannot-conntect-test.patch
  hack/0001-test-e2e-image.patch
  hack/0001-test-e2e-reduce-test-log.patch
  hack/k8s-e2e-v1.25.16.patch
  hack/kubesmartcluster.yaml.tmpl
Labels: size/m
