Repository everoute/everoute, pull requests merged in 2024-08, with the labels that each got.

#833 feat(cni): reject svc with no endpoints
  .github/workflows/ci.yaml
  go.mod
  go.sum
  pkg/agent/datapath/natBridge.go
Labels: size/s

#876 fix(ER-860): auth with tower from env
  plugin/tower/pkg/register/manager.go
  plugin/tower/pkg/register/manager_test.go
Labels: size/xs

#878 fix(ER-871): bridge replays flows based on connected signal
  go.mod
  go.sum
  pkg/agent/datapath/baseBridge.go
  pkg/agent/datapath/multiBridgeDatapath.go
Labels: size/s

#881 fix(ER-871): bridge replays flows based on connected signal
  go.mod
  go.sum
  pkg/agent/datapath/baseBridge.go
  pkg/agent/datapath/multiBridgeDatapath.go
Labels: size/s

#877 feat: add pod.k8scluster api
  Makefile
  deploy/chart/templates/crds/pod.everoute.io_k8sclusters.yaml
  deploy/everoute.yaml
  pkg/agent/controller/proxy/ipset_test.go
  pkg/apis/pod/doc.go
  pkg/apis/pod/install/install.go
  pkg/apis/pod/register.go
  pkg/apis/pod/v1alpha1/doc.go
  pkg/apis/pod/v1alpha1/register.go
  pkg/apis/pod/v1alpha1/types.go
  pkg/apis/pod/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/pod/zz_generated.deepcopy.go
  pkg/client/clientset_generated/clientset/clientset.go
  pkg/client/clientset_generated/clientset/fake/clientset_generated.go
  pkg/client/clientset_generated/clientset/fake/register.go
  pkg/client/clientset_generated/clientset/scheme/register.go
  pkg/client/clientset_generated/clientset/typed/pod/v1alpha1/doc.go
  pkg/client/clientset_generated/clientset/typed/pod/v1alpha1/fake/doc.go
  pkg/client/clientset_generated/clientset/typed/pod/v1alpha1/fake/fake_k8scluster.go
  pkg/client/clientset_generated/clientset/typed/pod/v1alpha1/fake/fake_pod_client.go
  pkg/client/clientset_generated/clientset/typed/pod/v1alpha1/generated_expansion.go
  pkg/client/clientset_generated/clientset/typed/pod/v1alpha1/k8scluster.go
  pkg/client/clientset_generated/clientset/typed/pod/v1alpha1/pod_client.go
  pkg/client/informers_generated/externalversions/factory.go
  pkg/client/informers_generated/externalversions/generic.go
  pkg/client/informers_generated/externalversions/pod/interface.go
  pkg/client/informers_generated/externalversions/pod/v1alpha1/interface.go
  pkg/client/informers_generated/externalversions/pod/v1alpha1/k8scluster.go
  pkg/client/listers_generated/pod/v1alpha1/expansion_generated.go
  pkg/client/listers_generated/pod/v1alpha1/k8scluster.go
Labels: size/m

#880 fix: er-872 must add system policy before add global rule policy
  cmd/everoute-agent/config.go
  cmd/everoute-agent/main.go
  pkg/agent/controller/policy/global_policy_controller.go
  pkg/agent/controller/policy/global_policy_controller_test.go
  pkg/agent/controller/policy/policy_controller.go
  pkg/agent/controller/policy/policy_controller_test.go
  pkg/agent/controller/policy/suite_test.go
  pkg/constants/constants.go
  tests/e2e/scripts/agent-setup.sh
Labels: size/s

#882 fix: er-872 must add system policy before add global rule policy
  cmd/everoute-agent/config.go
  cmd/everoute-agent/main.go
  pkg/agent/controller/policy/global_policy_controller.go
  pkg/agent/controller/policy/global_policy_controller_test.go
  pkg/agent/controller/policy/policy_controller.go
  pkg/agent/controller/policy/policy_controller_test.go
  pkg/agent/controller/policy/suite_test.go
  pkg/constants/constants.go
  tests/e2e/scripts/agent-setup.sh
Labels: size/s

#883 feat: doesn't make set when add processed system policy
  pkg/agent/controller/policy/policy_controller.go
Labels: size/s

#885 feat: tidy constants
  cmd/everoute-agent/config.go
  cmd/everoute-agent/main.go
  cmd/everoute-controller/config.go
  cmd/everoute-controller/main.go
  pkg/agent/controller/ippool/controller.go
  pkg/agent/controller/policy/policy_controller.go
  pkg/agent/controller/policy/suite_test.go
  pkg/agent/datapath/group_id.go
  pkg/agent/datapath/localBridge.go
  pkg/agent/datapath/localBridgeOverlay.go
  pkg/agent/datapath/multiBridgeDatapath.go
  pkg/agent/datapath/natBridge.go
  pkg/agent/datapath/uplinkBridgeOverlay.go
  pkg/agent/datapath/utils.go
  pkg/agent/proxy/iptables/proxy_iptables.go
  pkg/agent/proxy/iptables/proxy_iptables_test.go
  pkg/agent/proxy/overlay_route.go
  pkg/agent/proxy/route.go
  pkg/agent/rpcserver/cni.go
  pkg/constants/cni/constants.go
  pkg/constants/constants.go
  pkg/constants/ms/constants.go
  pkg/constants/ms/pod_policy.go
  pkg/controller/endpoint/strict_mac_ep.go
  pkg/controller/endpoint/strict_mac_ep_test.go
  pkg/controller/ipam/endpoint.go
  pkg/controller/ipam/endpoint_test.go
  pkg/metrics/agent_metrics.go
  pkg/metrics/controller_metrics.go
  pkg/metrics/ip_migrate_count.go
  pkg/utils/cni.go
  plugin/tower/pkg/controller/global/controller_test.go
  plugin/tower/pkg/controller/policy/controller.go
  plugin/tower/pkg/controller/policy/controller_test.go
Labels: size/m

#884 feat: sync sks kubeconfig from tower
  Makefile
  build/images/generate/Dockerfile
  cmd/everoute-controller/main.go
  go.mod
  go.sum
  pkg/constants/ms/constants.go
  pkg/constants/ms/pod_policy.go
  pkg/source/channel.go
  plugin/tower/pkg/client/client.go
  plugin/tower/pkg/client/client_test.go
  plugin/tower/pkg/controller/secret/process.go
  plugin/tower/pkg/controller/secret/process_test.go
  plugin/tower/pkg/controller/secret/suit_test.go
  plugin/tower/pkg/controller/secret/watch.go
  plugin/tower/pkg/informer/reflector.go
  plugin/tower/pkg/register/manager.go
  plugin/tower/pkg/register/manager_test.go
  tests/e2e/framework/config/config.go
  tests/mocks/mock_client.go
Labels: size/l

#886 feat: sync elfid from tower
  pkg/constants/ms/constants.go
  plugin/tower/pkg/controller/computecluster/controller.go
  plugin/tower/pkg/controller/computecluster/controller_test.go
  plugin/tower/pkg/controller/computecluster/suit_test.go
  plugin/tower/pkg/controller/secret/process.go
  plugin/tower/pkg/register/manager.go
  plugin/tower/pkg/schema/types.go
  plugin/tower/pkg/schema/types.graphqls
  plugin/tower/pkg/server/fake/graph/generated/generated.go
Labels: size/m

#889 ci: fix secret unittest
  plugin/tower/pkg/controller/secret/process_test.go
Labels: size/xs

#890 feat: add sync source
  pkg/source/with_sync_cache.go
  plugin/tower/pkg/controller/secret/process.go
Labels: size/s

#891 feat: add ip block in policy applyTo
  deploy/chart/templates/crds/security.everoute.io_securitypolicies.yaml
  deploy/everoute.yaml
  docs/content/en/docs/reference/apidocs.html
  pkg/agent/controller/policy/policy_controller_test.go
  pkg/apis/security/v1alpha1/types.go
  pkg/apis/security/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/policy/group_generator.go
Labels: size/s

#892 feat: set datapath-id on connect to switch
  pkg/agent/datapath/multiBridgeDatapath.go
Labels: size/s

#888 fix: data race when reconnect and print log
  pkg/agent/datapath/multiBridgeDatapath.go
Labels: size/xs

#893 chore: update readme and notice
  NOTICE.md
  README.md
  build/images/generate/Dockerfile
  docs/assets/everoute_arch.svg.png
  pkg/monitor/agent.go
  tests/e2e/framework/endpoint/tower/tower.go
Labels: size/m

#894 feat: k8scluster api add spec.controlplaneavailabel
  deploy/chart/templates/crds/pod.everoute.io_k8sclusters.yaml
  deploy/everoute.yaml
  pkg/apis/pod/v1alpha1/types.go
Labels: size/xs
