Repository everoute/everoute, pull requests merged in 2024-06, with the labels that each got.

#818 ci: test k8se2e
  .github/workflows/ci.yaml
  hack/k8s-e2e-v1.25.16.patch
Labels: size/m

#828 feat: plugin tower support logging
  deploy/chart/templates/crds/security.everoute.io_globalpolicies.yaml
  deploy/chart/templates/crds/security.everoute.io_securitypolicies.yaml
  deploy/everoute.yaml
  docs/content/en/docs/reference/apidocs.html
  go.mod
  go.sum
  pkg/apis/security/v1alpha1/types.go
  pkg/apis/security/v1alpha1/zz_generated.deepcopy.go
  plugin/tower/pkg/controller/global/controller.go
  plugin/tower/pkg/controller/global/controller_test.go
  plugin/tower/pkg/controller/policy/controller.go
  plugin/tower/pkg/controller/policy/controller_test.go
  plugin/tower/pkg/schema/policy_types.go
  plugin/tower/pkg/schema/policy_types.graphqls
  plugin/tower/pkg/schema/types.go
  plugin/tower/pkg/schema/types.graphqls
  plugin/tower/pkg/server/fake/graph/generated/generated.go
Labels: size/m

#827 fix: set policy bridge flow in table0 has different priority
  pkg/agent/datapath/policyBridge.go
Labels: size/xs

#826 ci(build): allow building pre-release packages
  .github/workflows/build.yaml
Labels: size/xs

#831 ci: fix ut
  pkg/agent/controller/policy/policy_controller_test.go
  pkg/agent/controller/proxy/controller_test.go
Labels: size/xs

#830 ci: fix some ci related problems
  .github/workflows/build.yaml
  .github/workflows/ci.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/labeler.yaml
  Makefile
  deploy/chart/templates/controller/role.yaml
  deploy/everoute.yaml
  pkg/controller/k8s/endpoints_controller_test.go
Labels: size/s

#832 fix(cni): add net.netfilter.nf_conntrack_tcp_be_liberal = 1
  build/script/init_agent
Labels: size/xs

#834 feat: change svc cache
  .github/workflows/ci.yaml
  Makefile
  cmd/everoute-agent/main.go
  pkg/agent/controller/proxy/cache/backend_cache.go
  pkg/agent/controller/proxy/cache/service_cache.go
  pkg/agent/controller/proxy/cache/service_cache_test.go
  pkg/agent/controller/proxy/cache/service_port_cache.go
  pkg/agent/controller/proxy/cache/utils.go
  pkg/agent/controller/proxy/controller.go
  pkg/agent/controller/proxy/controller_test.go
  pkg/agent/controller/proxy/ipset_test.go
  pkg/agent/controller/proxy/suit_test.go
  pkg/agent/datapath/cache/svc_index.go
  pkg/agent/datapath/cache/svc_ovs_info.go
  pkg/agent/datapath/natBridge.go
  pkg/agent/rpcserver/rule.go
  pkg/apis/rpc/v1alpha1/rule.pb.go
  pkg/apis/rpc/v1alpha1/rule.proto
Labels: size/xl

#836 fix(er-749): re-sync tower resources every 30-60 minutes
  pkg/webhook/validates/crd_validate.go
  pkg/webhook/validates/crd_validate_test.go
  plugin/tower/pkg/informer/reflector.go
Labels: size/s

#840 fix: group not found err
  pkg/agent/controller/policy/policy_controller.go
  pkg/agent/controller/policy/policy_controller_helper.go
  pkg/agent/controller/policy/policy_controller_helper_test.go
  pkg/types/err.go
Labels: size/s

#837 将优先级和 tier 通过 grpc 导出
  build/images/generate/Dockerfile
  pkg/agent/datapath/multiBridgeDatapath.go
  pkg/agent/rpcserver/collector.go
  pkg/apis/rpc/v1alpha1/collector.pb.go
  pkg/apis/rpc/v1alpha1/collector.proto
Labels: size/s

#838 feat: add nodeport and lb flow
  pkg/agent/controller/proxy/cache/service_cache.go
  pkg/agent/controller/proxy/cache/service_cache_test.go
  pkg/agent/controller/proxy/controller.go
  pkg/agent/controller/proxy/controller_test.go
  pkg/agent/datapath/natBridge.go
Labels: size/m

#853 fix(cni): ignore ipset already add/del error
  pkg/agent/controller/proxy/ipset.go
Labels: size/xs

#845 fix(cni): delete error apiserver param check
  cmd/everoute-agent/config.go
  cmd/everoute-controller/config.go
Labels: size/s

#846 fix(cni): gw-ep endpoint doesn't need to check by webhook
  cmd/everoute-agent/main.go
  deploy/chart/templates/controller/webhook.yaml
  deploy/everoute.yaml
  pkg/constants/constants.go
Labels: size/s

#844 feat: storage flowid/groupid instead of flow/group in cache
  pkg/agent/controller/proxy/controller_test.go
  pkg/agent/controller/proxy/suit_test.go
  pkg/agent/datapath/cache/svc_index.go
  pkg/agent/datapath/cache/svc_ovs_info.go
  pkg/agent/datapath/natBridge.go
  pkg/agent/rpcserver/rule.go
Labels: size/m

#852 fix(cni): support access to svc from local node
  pkg/agent/proxy/iptables/overlay_mode.go
  pkg/agent/proxy/iptables/proxy_iptables.go
  pkg/agent/proxy/iptables/route_mode.go
  pkg/constants/constants.go
Labels: size/s

#855 fix(cni): support serviceport del when service exists
  .github/workflows/ci.yaml
  pkg/agent/controller/proxy/controller.go
  pkg/agent/controller/proxy/controller_test.go
  pkg/agent/datapath/natBridge.go
Labels: size/s

#854 fix(ut): ipset test data race
  pkg/agent/controller/proxy/ipset_test.go
Labels: size/xs

#857 fix(cni): sync ipset when init everoute-agent
  cmd/everoute-agent/main.go
  pkg/agent/controller/proxy/ipset.go
Labels: size/m

#858 feat: add controller metric
  cmd/everoute-controller/main.go
  go.mod
  pkg/constants/constants.go
  pkg/controller/endpoint/endpoint_controller.go
  pkg/controller/endpoint/endpoint_controller_test.go
  pkg/metrics/controller_metrics.go
  pkg/metrics/ip_migrate_count.go
Labels: size/m
