Repository everoute/everoute, pull requests merged in 2024-07, with the labels that each got.

#859 ci: add hostport k8se2e
  .github/workflows/ci.yaml
Labels: size/xs

#860 feat(ms): add agent arp metrics
  cmd/everoute-agent/main.go
  go.mod
  pkg/agent/controller/policy/suite_test.go
  pkg/agent/datapath/localBridge.go
  pkg/agent/datapath/multiBridgeDatapath.go
  pkg/agent/datapath/multiBridgeDatapath_test.go
  pkg/agent/datapath/utils.go
  pkg/constants/constants.go
  pkg/metrics/agent_metrics.go
Labels: size/s

#861 fix: drop block rule reverse traffic
  pkg/agent/controller/policy/cache/rule.go
  pkg/agent/controller/policy/cache/rule_test.go
  pkg/agent/controller/policy/policy_controller.go
  pkg/agent/controller/policy/policy_controller_helper.go
Labels: size/s

#862 feat(ms): add policy rule entry metrics in agent
  pkg/agent/controller/policy/global_policy_controller.go
  pkg/agent/controller/policy/policy_controller.go
  pkg/agent/controller/policy/policy_controller_helper.go
  pkg/agent/datapath/multiBridgeDatapath.go
  pkg/agent/datapath/multiBridgeDatapath_test.go
  pkg/agent/datapath/utils.go
  pkg/constants/constants.go
  pkg/metrics/agent_metrics.go
  plugin/tower/pkg/controller/global/controller_test.go
  plugin/tower/pkg/controller/policy/controller.go
  plugin/tower/pkg/controller/policy/controller_test.go
Labels: size/m

#864 fix: groupid replay
  go.mod
  go.sum
  pkg/agent/datapath/cache/svc_ovs_info.go
  pkg/agent/datapath/group_id.go
  pkg/agent/datapath/id_generate.go
  pkg/agent/datapath/multiBridgeDatapath.go
  pkg/agent/datapath/natBridge.go
  pkg/constants/constants.go
Labels: size/m

#866 fix(ER-844): bump ofnet version
  go.mod
  go.sum
Labels: size/xs

#870 test: fix dp test
  pkg/agent/datapath/uplinkBridgeOverlay_test.go
Labels: size/xs

#871 test: fix proxy ut failed by get svc
  pkg/agent/controller/proxy/controller_test.go
Labels: size/xs

#868 feat: do not drop ct invalid pkt in policy bridge
  pkg/agent/datapath/policyBridge.go
Labels: size/s

#869 fix: format ip and port list in tower policy rule
  plugin/tower/pkg/controller/policy/controller.go
  plugin/tower/pkg/controller/policy/controller_test.go
Labels: size/xs

#873 fix: do not check inv pkt in alg flows
  pkg/agent/datapath/policyBridge.go
Labels: size/xs

#874 fix: do not check inv pkt in alg flows
  pkg/agent/datapath/policyBridge.go
Labels: size/xs
