Repository everoute/everoute, pull requests merged in 2024-09, with the labels that each got.

#895 feat: transfer pod securitypolicy
  pkg/constants/ms/pod_policy.go
  pkg/utils/utils.go
  plugin/tower/pkg/controller/policy/controller.go
  plugin/tower/pkg/controller/policy/controller_test.go
  plugin/tower/pkg/controller/policy/suite_test.go
  plugin/tower/pkg/register/manager.go
  plugin/tower/pkg/register/manager_test.go
  plugin/tower/pkg/schema/policy_types.go
  plugin/tower/pkg/schema/policy_types.graphqls
  plugin/tower/pkg/server/fake/graph/generated/generated.go
  plugin/tower/pkg/utils/testing/builder.go
Labels: size/m

#896 feat: print column kscname and kscnamespace
  deploy/chart/templates/crds/pod.everoute.io_k8sclusters.yaml
  deploy/everoute.yaml
  pkg/apis/pod/v1alpha1/types.go
Labels: size/xs

#898 feat: crdfactory don't set namespace
  plugin/tower/pkg/controller/endpoint/controller.go
  plugin/tower/pkg/controller/policy/controller.go
  plugin/tower/pkg/register/manager.go
Labels: size/s

#899 ci: fix unit-test
  plugin/tower/pkg/controller/policy/controller_test.go
Labels: size/xs

#900 fix: typo on func sentARPRequest
  pkg/agent/datapath/multiBridgeDatapath.go
Labels: size/xs

#901 feat: add k8scluster webhook
  cmd/everoute-controller/main.go
  deploy/chart/templates/controller/role.yaml
  deploy/chart/templates/controller/webhook.yaml
  deploy/everoute.yaml
  pkg/webhook/validates/crd_validate.go
  pkg/webhook/validates/crd_validate_test.go
  pkg/webhook/validates/suite_test.go
Labels: size/xs

#902 feat: add webhook for ipblock in sp applyTo
  pkg/webhook/validates/crd_validate.go
  pkg/webhook/validates/crd_validate_test.go
Labels: size/s

#903 fix: er924 set match monitor drop priority higher than blocklist
  pkg/agent/datapath/multiBridgeDatapath_test.go
  pkg/agent/datapath/policyBridge.go
  pkg/constants/constants.go
Labels: size/xs

#904 feat: move strictmac controller to sks-plugin
  cmd/everoute-controller/main.go
  pkg/constants/ms/pod_policy.go
  pkg/controller/endpoint/endpoint_controller_test.go
  pkg/controller/endpoint/strict_mac_ep.go
  pkg/controller/endpoint/strict_mac_ep_test.go
  pkg/controller/endpoint/suit_test.go
Labels: size/m

#905 fix: policy rule with same src and dst cidr block
  pkg/agent/controller/policy/cache/rule.go
  pkg/agent/controller/policy/policy_controller_test.go
Labels: size/xs
