Repository everoute/everoute, pull requests merged in 2024-11, with the labels that each got.

#921 fix(ER-959): set cni port unmanaged in network manager
  build/images/release/Dockerfile
  build/script/init_agent
  deploy/chart/templates/agent/agent.yaml
  deploy/everoute.yaml
  deploy/microsegment/chart/templates/agent/agent.yaml
Labels: size/s

#920 style: minify log about securitypolicy
  cmd/everoute-agent/main.go
  pkg/agent/controller/ippool/suit_test.go
  pkg/agent/controller/overlay/suit_test.go
  pkg/agent/controller/policy/cache/group.go
  pkg/agent/controller/policy/cache/helper.go
  pkg/agent/controller/policy/cache/helper_test.go
  pkg/agent/controller/policy/cache/rule.go
  pkg/agent/controller/policy/global_policy_controller.go
  pkg/agent/controller/policy/policy_controller.go
  pkg/agent/controller/policy/policy_controller_test.go
  pkg/agent/controller/policy/suite_test.go
  pkg/agent/controller/proxy/suit_test.go
  pkg/agent/datapath/baseBridge.go
  pkg/agent/datapath/clsBridge.go
  pkg/agent/datapath/localBridge.go
  pkg/agent/datapath/multiBridgeDatapath.go
  pkg/agent/datapath/multiBridgeDatapath_test.go
  pkg/agent/datapath/policyBridge.go
  pkg/agent/datapath/uplinkBridge.go
  pkg/agent/datapath/utils.go
  pkg/labels/selector.go
  pkg/types/context.go
  pkg/utils/utils.go
  plugin/tower/pkg/controller/endpoint/controller.go
Labels: size/m

#923 chore: upgrade gci to 0.13.5 and format code
  Makefile
  build/images/generate/Dockerfile
  pkg/agent/controller/overlay/controller.go
  pkg/agent/controller/overlay/predicate_test.go
  pkg/agent/controller/proxy/cache/service_cache_test.go
  pkg/agent/controller/proxy/controller_test.go
  pkg/agent/datapath/clsBridge.go
  pkg/apis/agent/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/group/v1alpha1/types_test.go
  pkg/apis/group/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/security/v1alpha1/types.go
  pkg/apis/security/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset_generated/clientset/fake/register.go
  pkg/client/clientset_generated/clientset/scheme/register.go
  pkg/controller/endpoint/endpoint_controller_test.go
  pkg/controller/k8s/node_controller_test.go
  pkg/utils/arptables/arptables.go
  tests/e2e/framework/endpoint/tower/provider.go
Labels: size/xs

#924 fix: should add icmp reverse rule for block policy
  pkg/agent/controller/policy/cache/rule.go
  pkg/agent/controller/policy/cache/rule_test.go
  pkg/agent/controller/policy/policy_controller.go
  pkg/agent/datapath/policyBridge.go
  pkg/constants/constants.go
Labels: size/m

#926 test: run securitypolicy e2e for k8s cni
  .github/workflows/ci.yaml
  Makefile
  build/images/net-utils/Dockerfile
  go.mod
  go.sum
  tests/e2e/cases/security_test.go
  tests/e2e/framework/config/config.go
  tests/e2e/framework/endpoint/manager.go
  tests/e2e/framework/endpoint/pod/provider.go
  tests/e2e/framework/framework.go
  tests/e2e/framework/globalpolicy/provider.go
  tests/e2e/framework/node/agent.go
  tests/e2e/framework/node/node.go
  tests/e2e/tools/net-utils/command/server.go
Labels: size/l

#929 fix(er-958): clean ct should match icmp type and code
  pkg/agent/controller/policy/cache/rule.go
  pkg/agent/controller/policy/cache/rule_test.go
  pkg/agent/controller/policy/policy_controller_helper.go
  pkg/agent/datapath/multiBridgeDatapath.go
  pkg/agent/datapath/multiBridgeDatapath_test.go
  pkg/agent/datapath/policyBridge.go
  pkg/agent/datapath/utils.go
Labels: size/s

#928 refactor: modify datapath data model to reduce memory usage for evero…
  pkg/agent/controller/policy/cache/rule.go
  pkg/agent/controller/policy/cache/rule_test.go
  pkg/agent/controller/policy/global_policy_controller.go
  pkg/agent/controller/policy/policy_controller.go
  pkg/agent/controller/policy/policy_controller_test.go
  pkg/agent/datapath/multiBridgeDatapath.go
  pkg/agent/datapath/multiBridgeDatapath_test.go
  pkg/agent/datapath/utils.go
Labels: size/m

#931 fix(er-958): clean ct should match icmp type and code
  pkg/agent/controller/policy/cache/rule.go
  pkg/agent/controller/policy/cache/rule_test.go
  pkg/agent/controller/policy/policy_controller_helper.go
  pkg/agent/datapath/multiBridgeDatapath.go
  pkg/agent/datapath/multiBridgeDatapath_test.go
  pkg/agent/datapath/policyBridge.go
  pkg/agent/datapath/utils.go
Labels: size/s

#932 [pick] refactor: modify datapath data model to reduce memory usage for evero…
  pkg/agent/controller/policy/cache/rule.go
  pkg/agent/controller/policy/cache/rule_test.go
  pkg/agent/controller/policy/global_policy_controller.go
  pkg/agent/controller/policy/policy_controller.go
  pkg/agent/controller/policy/policy_controller_test.go
  pkg/agent/datapath/multiBridgeDatapath.go
  pkg/agent/datapath/multiBridgeDatapath_test.go
  pkg/agent/datapath/utils.go
Labels: size/m

#933 refactor: converted ip string to bytes in advance to reduce clean ct …
  pkg/agent/datapath/multiBridgeDatapath.go
  pkg/agent/datapath/rule.go
  pkg/agent/datapath/rule_test.go
  pkg/agent/datapath/utils.go
  pkg/agent/datapath/utils_test.go
Labels: size/m

#936 fix(er-789): add predicate when update resource to avoid process when…
  pkg/agent/controller/policy/policy_controller.go
  pkg/agent/datapath/multiBridgeDatapath.go
Labels: size/s

#937 fix(er-789): add predicate when update resource to avoid process when…
  pkg/agent/controller/policy/policy_controller.go
  pkg/agent/datapath/multiBridgeDatapath.go
Labels: size/s
