Repository everoute/everoute, pull requests merged in 2024-04, with the labels that each got.

#786 fix(ER-708): skip match monitor tier3 ingress when ct match monitor drop
  pkg/agent/datapath/multiBridgeDatapath_test.go
  pkg/agent/datapath/policyBridge.go
Labels: size/m

#788 fix: fatal when lose groupmemberpatch delete event
  go.mod
  go.sum
  pkg/agent/controller/policy/policy_controller.go
Labels: size/s

#789 fix: fatal when lose groupmemberpatch delete event
  pkg/agent/controller/policy/policy_controller.go
Labels: size/xs

#791 fix: delete rule should check other policyRuleReference
  pkg/agent/controller/policy/policy_controller.go
  pkg/agent/datapath/multiBridgeDatapath.go
Labels: size/s

#793 fix: check externalIDs when merge old ip to agentinfo
  pkg/constants/constants.go
  pkg/controller/endpoint/endpoint_controller.go
  pkg/controller/endpoint/suit_test.go
  pkg/monitor/agent.go
  pkg/monitor/agent_test.go
Labels: size/s

#796 fix: check externalIDs when merge old ip to agentinfo
  pkg/constants/constants.go
  pkg/controller/endpoint/endpoint_controller.go
  pkg/controller/endpoint/suit_test.go
  pkg/monitor/agent.go
  pkg/monitor/agent_test.go
Labels: size/s

#794 feat: support logging connection match security policy
  deploy/chart/templates/crds/security.everoute.io_globalpolicies.yaml
  deploy/chart/templates/crds/security.everoute.io_securitypolicies.yaml
  deploy/everoute.yaml
  docs/content/en/docs/reference/apidocs.html
  pkg/apis/security/v1alpha1/types.go
  pkg/apis/security/v1alpha1/zz_generated.deepcopy.go
Labels: size/m
