Repository everoute/everoute, pull requests merged in 2024-05, with the labels that each got.

#790 feat: add Priority and Isblocklist in securitypolicy api and webhook
  deploy/chart/templates/crds/security.everoute.io_securitypolicies.yaml
  deploy/everoute.yaml
  docs/content/en/docs/reference/apidocs.html
  pkg/apis/security/v1alpha1/types.go
  pkg/webhook/validates/crd_validate.go
  pkg/webhook/validates/crd_validate_test.go
Labels: size/s

#798 feat: implement securitypolicy priority and blocklist
  pkg/agent/controller/policy/cache/rule.go
  pkg/agent/controller/policy/policy_controller.go
  pkg/agent/controller/policy/policy_controller_helper.go
  pkg/constants/constants.go
Labels: size/s

#800 ut: fix monitor ut
  pkg/monitor/agent_test.go
Labels: size/xs

#799 feat: set internal policy priority
  plugin/tower/pkg/controller/policy/controller.go
Labels: size/xs

#802 feat: add blocklist e2e
  pkg/agent/controller/proxy/controller_test.go
  tests/e2e/cases/security_test.go
Labels: size/xs

#803 feat: set default rule priority
  deploy/chart/templates/crds/security.everoute.io_securitypolicies.yaml
  deploy/everoute.yaml
  docs/content/en/docs/reference/apidocs.html
  pkg/agent/controller/policy/policy_controller_helper.go
  pkg/apis/security/v1alpha1/types.go
  pkg/constants/constants.go
  tests/e2e/cases/security_mode.go
Labels: size/s

#801 feat: transform tower blocklist datamodel to securitypolicy api
  plugin/tower/pkg/controller/policy/controller.go
  plugin/tower/pkg/controller/policy/controller_test.go
  plugin/tower/pkg/schema/policy_types.go
  plugin/tower/pkg/schema/policy_types.graphqls
  plugin/tower/pkg/server/fake/graph/generated/generated.go
Labels: size/s

#805 refactor: controller doesn't generate groupmemberspatch
  pkg/constants/constants.go
  pkg/controller/group/group_controller.go
  pkg/controller/group/group_controller_test.go
Labels: size/m

#806 feat: generate empty groupmembers
  pkg/apis/group/v1alpha1/types.go
  pkg/apis/group/v1alpha1/types_test.go
  pkg/controller/group/group_controller.go
  pkg/controller/group/group_controller_test.go
Labels: size/s

#808 feat: group agent reconcile for policy
  pkg/agent/controller/policy/cache/group.go
  pkg/agent/controller/policy/cache/group_test.go
  pkg/agent/controller/policy/cache/helper.go
  pkg/agent/controller/policy/cache/helper_test.go
  pkg/agent/controller/policy/cache/rule.go
  pkg/agent/controller/policy/policy_controller.go
  pkg/agent/controller/policy/policy_controller_helper.go
  pkg/agent/controller/policy/policy_controller_test.go
  pkg/controller/group/group_controller.go
Labels: size/l

#810 feat: agent reconcile groupmembers
  pkg/agent/controller/policy/cache/helper.go
  pkg/agent/controller/policy/cache/rule.go
  pkg/agent/controller/policy/policy_controller.go
Labels: size/s

#813 feat: add ip range and multi ips support in sp
  go.mod
  go.sum
  plugin/tower/pkg/controller/policy/controller.go
  plugin/tower/pkg/controller/policy/controller_test.go
  plugin/tower/pkg/schema/policy_types.go
  plugin/tower/pkg/utils/testing/builder.go
Labels: size/m

#815 feat(cni): sync attached ip in ext id before start cni agent
  build/script/start-everoute-agent
  hack/kubesmartcluster.yaml.tmpl
  hack/kubesmartcluster_idc.yaml.tmpl
Labels: size/s

#814 refactor: refactor groupmembers, delete groupmemberspatch
  pkg/agent/controller/policy/cache/group.go
  pkg/agent/controller/policy/cache/group_test.go
  pkg/agent/controller/policy/cache/helper.go
  pkg/agent/controller/policy/cache/helper_test.go
  pkg/agent/controller/policy/cache/rule.go
  pkg/agent/controller/policy/policy_controller.go
  pkg/agent/controller/policy/policy_controller_helper.go
  pkg/agent/controller/policy/policy_controller_test.go
  pkg/agent/controller/policy/suite_test.go
  pkg/apis/group/v1alpha1/types.go
  pkg/apis/group/v1alpha1/types_test.go
  pkg/constants/constants.go
  pkg/controller/group/group_controller.go
  pkg/controller/group/group_controller_test.go
Labels: size/xl

#817 feat: blocklist and allowlist with same policy priority has different flow priority
  pkg/agent/controller/policy/cache/rule.go
  pkg/agent/controller/policy/policy_controller_helper.go
  pkg/agent/controller/policy/policy_controller_test.go
  pkg/agent/controller/policy/suite_test.go
  pkg/constants/constants.go
  pkg/webhook/validates/crd_validate.go
  pkg/webhook/validates/crd_validate_test.go
  tests/e2e/cases/security_mode.go
Labels: size/s

#823 fix: start strictmac ctrl in controller
  cmd/everoute-controller/main.go
  pkg/controller/endpoint/strict_mac_ep.go
  pkg/controller/endpoint/strict_mac_ep_test.go
Labels: size/s

#824 feat(dp): set mutex timeout to 5 mins
  go.mod
  go.sum
  pkg/agent/datapath/multiBridgeDatapath.go
Labels: size/s

#822 feat: set priority default value to 30
  .github/workflows/ci.yaml
  deploy/chart/templates/crds/security.everoute.io_securitypolicies.yaml
  deploy/everoute.yaml
  docs/content/en/docs/reference/apidocs.html
  pkg/agent/controller/policy/policy_controller_test.go
  pkg/apis/security/v1alpha1/types.go
  plugin/tower/pkg/controller/policy/controller.go
  plugin/tower/pkg/controller/policy/controller_test.go
  tests/e2e/cases/security_mode.go
Labels: size/s
