Repository everoute/everoute, pull requests merged in 2024-01, with the labels that each got.

#743 feat: use everoute ipam for agent init and cni
  Makefile
  cmd/everoute-agent/config.go
  cmd/everoute-agent/main.go
  deploy/chart/templates/agent/role.yaml
  deploy/chart/templates/config.yaml
  deploy/chart/templates/crds/ipam.everoute.io_ippools.yaml
  deploy/chart/values.yaml
  deploy/everoute.yaml
  go.mod
  go.sum
  pkg/agent/datapath/multiBridgeDatapath.go
  pkg/agent/rpcserver/cni.go
  pkg/constants/constants.go
  pkg/ipam/everoute_ipam.go
  pkg/ipam/host_local_ipam.go
  pkg/ipam/ipam.go
  pkg/utils/cni.go
Labels: size/l

#742 feat: controller pod tolerate control-plane role
  deploy/chart/templates/controller/controller.yaml
  deploy/everoute.yaml
Labels: size/xs

#744 feat: set everoute built-in ippool
  cmd/everoute-agent/config.go
  deploy/chart/templates/everoute_ippool.yaml
  deploy/chart/values.yaml
  pkg/agent/rpcserver/cni.go
  pkg/constants/constants.go
  pkg/ipam/everoute_ipam.go
Labels: size/s

#745 feat: watch ippool to set route and iptables rule of EVEROUTE-OUTPUT chain
  cmd/everoute-agent/main.go
  deploy/chart/values.yaml
  pkg/agent/controller/ippool/controller.go
  pkg/agent/datapath/multiBridgeDatapath.go
  pkg/agent/proxy/iptables/overlay_mode.go
  pkg/agent/proxy/iptables/proxy_iptables.go
  pkg/agent/proxy/overlay_route.go
  pkg/agent/proxy/route.go
Labels: size/l

#746 feat: set gw ippool private
  deploy/chart/templates/crds/ipam.everoute.io_ippools.yaml
  deploy/chart/templates/everoute_ippool.yaml
  deploy/chart/values.yaml
  deploy/everoute.yaml
  go.mod
  go.sum
Labels: size/s

#748 feat: watch ippool and setup ovsflow
  cmd/everoute-agent/config.go
  cmd/everoute-agent/main.go
  pkg/agent/controller/ippool/controller.go
  pkg/agent/datapath/baseBridge.go
  pkg/agent/datapath/localBridgeOverlay.go
  pkg/agent/datapath/multiBridgeDatapath.go
  pkg/agent/datapath/uplinkBridgeOverlay.go
  pkg/agent/datapath/utils.go
  pkg/agent/proxy/route.go
Labels: size/m

#755 fix: node controller ut must run after k8smanager start
  pkg/controller/k8s/node_controller_test.go
  pkg/controller/k8s/suite_test.go
Labels: size/xs

#753 feat: add ipam webhook
  cmd/everoute-controller/config.go
  cmd/everoute-controller/main.go
  deploy/chart/templates/config.yaml
  deploy/chart/templates/controller/role.yaml
  deploy/chart/templates/controller/webhook.yaml
  deploy/everoute.yaml
  pkg/constants/constants.go
  pkg/controller/common/webhook_controller.go
Labels: size/s

#758 fix(ER-649): update libopenflow
  go.mod
  go.sum
Labels: size/xs

#756 ci: k8s e2e run in idc
  .github/workflows/ci.yaml
  hack/kubesmartcluster_idc.yaml.tmpl
Labels: size/m

#759 feat: bump libopenflow dependence
  go.mod
  go.sum
Labels: size/xs

#760 test(monitor): fix unstable unit test
  pkg/monitor/agent_test.go
  pkg/monitor/ovsdb_test.go
  pkg/monitor/suite_test.go
Labels: size/xs

#754 feat: move cniargs type define from utils to types
  pkg/agent/rpcserver/cni.go
  pkg/ipam/everoute_ipam.go
  pkg/ipam/host_local_ipam.go
  pkg/ipam/ipam.go
  pkg/types/cni.go
  pkg/utils/cni.go
Labels: size/s

#757 feat: release gateway ip
  cmd/everoute-agent/main.go
  cmd/everoute-controller/config.go
  cmd/everoute-controller/main.go
  deploy/chart/templates/config.yaml
  deploy/chart/templates/controller/role.yaml
  deploy/chart/values.yaml
  deploy/everoute.yaml
  go.mod
  pkg/constants/constants.go
  pkg/controller/ipam/endpoint.go
  pkg/controller/ipam/endpoint_test.go
  pkg/controller/ipam/suit_test.go
  pkg/ipam/everoute_ipam.go
  pkg/ipam/release_gw_ip.go
  pkg/ipam/release_gw_ip_test.go
  pkg/ipam/suit_test.go
  pkg/utils/cni.go
Labels: size/m

#761 ci: everoute ipam ci
  .github/workflows/ci.yaml
  hack/ippool_ci.yaml
Labels: size/s
