Repository everoute/everoute, pull requests merged in 2025-02, with the labels that each got.

#950 ci: try 3 times to run unit-test
  .github/workflows/ci.yaml
Labels: size/xs

#951 ci: replace crypto version
  go.mod
  go.sum
  pkg/agent/controller/proxy/controller.go
  pkg/labels/selector.go
  pkg/utils/arptables/arptables.go
  plugin/tower/pkg/client/client.go
Labels: size/s

#952 fix: ip group with empty except and set in rule peers
  plugin/tower/pkg/controller/policy/controller.go
  plugin/tower/pkg/controller/policy/controller_test.go
  plugin/tower/pkg/utils/testing/builder.go
Labels: size/s

#953 feat: policy bridge flow init for forward packets to svm
  .golangci.yml
  go.mod
  go.sum
  pkg/agent/datapath/clsBridge.go
  pkg/agent/datapath/policyBridge.go
  pkg/constants/constants.go
Labels: size/m

#956 fix(ER-1108): process policy one by one when group changed
  pkg/agent/controller/policy/policy_controller.go
  tests/e2e/cases/security_test.go
Labels: size/s

#955 feat: add servicechain crd and agent config format
  .github/workflows/ci.yaml
  Makefile
  cmd/everoute-agent/config.go
  deploy/chart/templates/crds/servicechain.everoute.io_trafficredirects.yaml
  deploy/everoute.yaml
  deploy/microsegment/chart/templates/crds/servicechain.everoute.io_trafficredirects.yaml
  deploy/servicechain/chart/.helmignore
  deploy/servicechain/chart/Chart.yaml
  deploy/servicechain/chart/templates/crds/servicechain.everoute.io_trafficredirects.yaml
  deploy/servicechain/chart/values.yaml
  pkg/apis/servicechain/doc.go
  pkg/apis/servicechain/install/install.go
  pkg/apis/servicechain/register.go
  pkg/apis/servicechain/v1alpha1/doc.go
  pkg/apis/servicechain/v1alpha1/register.go
  pkg/apis/servicechain/v1alpha1/types.go
  pkg/apis/servicechain/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/servicechain/zz_generated.deepcopy.go
  pkg/client/clientset_generated/clientset/clientset.go
  pkg/client/clientset_generated/clientset/fake/clientset_generated.go
  pkg/client/clientset_generated/clientset/fake/register.go
  pkg/client/clientset_generated/clientset/scheme/register.go
  pkg/client/clientset_generated/clientset/typed/servicechain/v1alpha1/doc.go
  pkg/client/clientset_generated/clientset/typed/servicechain/v1alpha1/fake/doc.go
  pkg/client/clientset_generated/clientset/typed/servicechain/v1alpha1/fake/fake_servicechain_client.go
  pkg/client/clientset_generated/clientset/typed/servicechain/v1alpha1/fake/fake_trafficredirect.go
  pkg/client/clientset_generated/clientset/typed/servicechain/v1alpha1/generated_expansion.go
  pkg/client/clientset_generated/clientset/typed/servicechain/v1alpha1/servicechain_client.go
  pkg/client/clientset_generated/clientset/typed/servicechain/v1alpha1/trafficredirect.go
  pkg/client/informers_generated/externalversions/factory.go
  pkg/client/informers_generated/externalversions/generic.go
  pkg/client/informers_generated/externalversions/servicechain/interface.go
  pkg/client/informers_generated/externalversions/servicechain/v1alpha1/interface.go
  pkg/client/informers_generated/externalversions/servicechain/v1alpha1/trafficredirect.go
  pkg/client/listers_generated/servicechain/v1alpha1/expansion_generated.go
  pkg/client/listers_generated/servicechain/v1alpha1/trafficredirect.go
Labels: size/m

#957 fix(er-1028): set ip learning times
  .github/workflows/ci.yaml
  pkg/agent/datapath/multiBridgeDatapath.go
Labels: size/xs
